/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  Controller
 *  model: Controller
 *  expmt: 20-1940
 *  date:  January 16, 2022
 *  time:  1:03:43 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.4.11233
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


